# version: '3.8'

# services:
#   mysql:  
#     build:
#       context: ./mysql
#     ports:
#       - "3307:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: file_storage
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app-network

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5000:5000"
#     command: sh -c "sleep 10s ; python ./script/app.py"
#     networks:
#       - app-network
#     depends_on:
#       - mysql

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   mysql-data:


#   version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/script:/app
    networks:
      - app-network
    environment:
      FLASK_ENV: development
      MYSQL_HOST: host.docker.internal  # Use host.docker.internal to connect to MySQL on the host
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: file_storage



  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: