version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  flask:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - react
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
