# Build React static files
FROM node:14
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Serve the React app using a simple HTTP server
RUN npm install -g serve
CMD ["serve", "-s", "build"]
EXPOSE 3000