SELECT LAST_NAME, FIRST_NAME, AGENT_LEVEL AS AGEN FROM rcv_agent WHERE AGENT_SPECIALITY = 'us' ORDER BY last_name;


select DEST_DESCRIPTION, coUntRy, STATE, CITY, PRICE FROM rcv_destination WHERE (CounTRY = 'France' OR COUNTRY = 'Spain') AND price <= 100 ORDER BY COUNTRY ASC, CITY, DEST_DESCRIPTION ASC, PRICE;

SELECT FIRST_NAME AS "First", LAST_NAME AS "Last", CUSTOMER_PHONE AS "Phone", CUSTOMER_PROVINCE AS "Prov" FROM RCV_CUSTOMER WHERE CUSTOMER_PHONE LIKE '%310%' ORDER BY LAST_NAME, FIRST_NAME;